#!/usr/bin/env bash
# Copyright (c) 2026 Skuld, LLC. All rights reserved.
# Proprietary and confidential. Reverse engineering prohibited.
#
# Regenerates src/data/nodeAvailability.json — the single source of truth the
# Studio uses to decide which nodes are executable. It is produced by QG19's
# parity checker in the sibling skuldbot-documentation repo, comparing the Studio
# catalog against the compiler templates and the executor registry.
#
# Requires the sibling repos checked out next to skuldbot-studio:
#   skuldbot-documentation, skuldbot-compiler, skuldbot-executor
#
# The committed manifest is only ever replaced by a manifest demonstrably written
# in THIS run: the checker writes to a temp file, we validate that temp file is a
# fresh, well-formed QG19 manifest with nodes, and only then atomically move it
# into place. This guarantees QG19.6 ("availability source is generated"): a real
# generation failure (missing sibling repo, Python error, broken path) can never
# leave a stale manifest passing as freshly generated.

set -euo pipefail

STUDIO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${STUDIO_DIR}/src/data/nodeAvailability.json"
CHECKER="${STUDIO_DIR}/../skuldbot-documentation/scripts/quality/check_node_parity.py"

if [ ! -f "${CHECKER}" ]; then
  echo "ERROR: parity checker not found at ${CHECKER}" >&2
  echo "Check out skuldbot-documentation next to skuldbot-studio." >&2
  exit 1
fi

# Generate into a temp file in the SAME directory so the final move is atomic
# (same filesystem). The temp is always removed on exit, so an interrupted or
# failed run never leaves a partial artifact behind.
TMP_OUT="$(mktemp "${STUDIO_DIR}/src/data/.nodeAvailability.json.XXXXXX")"
trap 'rm -f "${TMP_OUT}"' EXIT

# The checker exits non-zero when parity debt remains (a known, expected state
# today). That exit code is acceptable ONLY because we independently verify below
# that it still wrote a valid manifest this run; we do not trust its exit code.
python3 "${CHECKER}" \
  --studio-dir "${STUDIO_DIR}" \
  --compiler-dir "${STUDIO_DIR}/../skuldbot-compiler/python" \
  --executor-dir "${STUDIO_DIR}/../skuldbot-executor/python" \
  --availability-json "${TMP_OUT}" || true

# Validate the freshly written temp: it must be valid JSON generated by QG19 in
# this run, with a non-empty nodes map. If the checker failed before writing, the
# temp is empty/invalid and this aborts (set -e) without touching the committed
# manifest.
python3 - "${TMP_OUT}" <<'PY'
import json
import sys

path = sys.argv[1]
try:
    with open(path, encoding="utf-8") as handle:
        data = json.load(handle)
except (OSError, json.JSONDecodeError) as exc:
    raise SystemExit(f"availability manifest was not generated this run: {exc}")

if data.get("generatedBy") != "QG19":
    raise SystemExit('generated manifest is missing generatedBy="QG19".')

nodes = data.get("nodes")
if not isinstance(nodes, dict) or not nodes:
    raise SystemExit("generated manifest has no nodes.")

print(f"validated freshly generated manifest: {len(nodes)} nodes")
PY

# Atomically replace the committed manifest with the freshly generated one.
mv -f "${TMP_OUT}" "${OUT}"
trap - EXIT

echo "Wrote ${OUT}"
